version: '3.8'

services:
  frontend:
    container_name: pong-frontend
    build: ./frontend/
    restart: always
    ports:
      - "5574:5574"
    networks:
      - pong-network
    volumes:
      - frontend-volume:/home/frontend-volume
  backend:
    container_name: pong-backend
    build: ./backend/
    restart: always
    networks:
      - pong-network
    volumes:
      - backend-volume:/home/backend-volume
  postgres_db:
    container_name: pong-database
    build: ./database/
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - pong-network
    volumes:
      - database:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - pong-network
networks:
  pong-network:
    driver: bridge
volumes:
  database:
  frontend-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/frontend/volume
  backend-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/backend/volume